import csv 
import pandas as pd
missing_val = ["?"]
df = pd.read_csv("main.csv" , na_values=missing_val)
print(df.shape)
df = df.dropna()
df.drop(["Unnamed: 0","Star_Name", "Star_Mass", "Star_Radius" , "Distance" , "Star_luminosity"] , axis=1 , inplace=True)
df["Star_Mass_1"].replace("0.7 - 1.0" , "0.85" , inplace = True)
df["Star_Mass_1"].replace("<20" , "15" , inplace=True)
df["Star_Mass_1"].replace('7–10' , "8.5" , inplace=True)
print(df["Star_Mass_1"].unique())
df["Star_Radius_1"].replace('60–881' , "470.5" , inplace=True)
df["Star_Radius_1"].replace('636-981' , "808.5" , inplace=True)
df["Star_Radius_1"].replace('516 - 1,050' , "783" , inplace=True)
df["Star_Radius_1"].replace('1,640 - 2,770' , "2205" , inplace=True)
df["Star_Radius_1"].replace( '1,540 - 1,730', "1635" , inplace=True)
print(df["Star_Radius_1"].unique())
df.reset_index(drop=True,inplace = True)
print(df.dtypes)
print(df.info())
print(df.describe())
df.to_csv("final.csv" , index=False)